import fs from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { chromium } from 'playwright';

const project=path.dirname(new URL(import.meta.url).pathname).replace(/^\/([A-Za-z]:)/,'$1');
const input=path.resolve(process.argv[2]??path.join(project,'player.json'));
const data=JSON.parse(await fs.readFile(input,'utf8'));
if(!data.player||!Array.isArray(data.clues)||data.clues.length!==3)throw Error('Need a player and exactly three clues');
if(data.player.length>24||data.clues.some(x=>typeof x!=='string'||x.length>56))throw Error('Player name max 24 characters; each clue max 56');
const slug=(data.slug??data.player.toLowerCase().replace(/[^a-z0-9]+/g,'-')).replace(/[^a-z0-9-]/g,'');
const out=path.resolve(process.argv[3]??path.join(project,'renders',slug));await fs.mkdir(out,{recursive:true});
const bgData=(await fs.readFile(path.join(project,'arena-background-v2.png'))).toString('base64');
const pressData=(await fs.readFile(path.join(project,'PressStart2P-Regular.ttf'))).toString('base64');
const silkData=(await fs.readFile(path.join(project,'Silkscreen-Regular.ttf'))).toString('base64');
const e=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(value,x,y,w,h,size,color='#F4F7FB',bold=false,center=false)=>{const arcade=size>=55||String(value)===data.player.toUpperCase()||['FACTS OVER FEELINGS','THE PLAYER IS','THE THREE CLUES','DAILY MYSTERY PLAYER','THE REVEAL'].includes(String(value))||/^CLUE [123] OF 3$/.test(String(value));return `<div style="position:absolute;left:${x}px;top:${y}px;width:${w}px;height:${h}px;display:flex;align-items:center;${center?'justify-content:center;text-align:center;':''}font:${arcade?'normal':bold?'bold':'normal'} ${size}px/1.12 '${arcade?'Press Start 2P':'Silkscreen'}';color:${color}">${value}</div>`};
const panel=(x,y,w,h,active=false)=>`<div style="position:absolute;left:${x}px;top:${y}px;width:${w}px;height:${h}px;box-sizing:border-box;background:${active?'#111827':'#0C111D'};border:${active?'4px solid #FF8A32':'2px solid #283348'};border-radius:10px"></div>`;
function frame(n,kicker,body){return `<!doctype html><html><head><meta charset="utf-8"><style>@font-face{font-family:'Press Start 2P';src:url(data:font/ttf;base64,${pressData}) format('truetype')}@font-face{font-family:'Silkscreen';src:url(data:font/ttf;base64,${silkData}) format('truetype')}</style></head><body style="margin:0"><main style="position:relative;width:1080px;height:1920px;overflow:hidden;background:#070A12 url(data:image/png;base64,${bgData}) center/cover no-repeat;font-family:Silkscreen"><div style="position:absolute;left:60px;top:55px;width:960px;height:10px;background:#FF8A32"></div>${t('FACTS OVER FEELINGS',70,95,940,62,31,'#F4F7FB')}${t(e(kicker.toUpperCase()),70,165,940,46,20,'#FF8A32')}${body}${t(`${n} / 5`,70,1752,200,42,29,'#AAB5C7',true)}${t('playfactsoverfeelings.com',70,1810,940,48,33,'#F4F7FB',true)}<div style="position:absolute;left:60px;top:1875px;width:960px;height:7px;background:#FF8A32"></div></main></body></html>`}
const pages=[];
pages.push(frame(1,'Daily mystery player',t('GUESS THE<br>MYSTERY PLAYER',70,275,940,235,55,'#F4F7FB')+t('?',220,590,640,700,420,'#FF8A32',false,true)+t('Three clues. One player.',70,1350,940,70,51,'#F4F7FB',true,true)+t('THE PLAYER CAN BE FROM ANY ERA',70,1450,940,70,31,'#FFC168',true,true)));
for(let i=1;i<=3;i++){let body=t(`CLUE ${i}`,70,290,940,110,66,'#F4F7FB')+t('Who is the player?',70,415,940,66,49,'#AAB5C7');for(let k=1;k<=3;k++){const y=590+(k-1)*260,active=k===i,shown=k<=i;body+=panel(70,y,940,210,active)+t(`0${k}  ${shown?'REVEALED':'LOCKED'}`,105,y+30,860,40,22,active?'#FF8A32':'#AAB5C7',true)+t(shown?e(data.clues[k-1].toUpperCase()):'?',105,y+82,860,112,47,active?'#F4F7FB':'#AAB5C7',true);}body+=t(i===3?'Make your guess before the reveal':'Next clue coming up',70,i===3?1500:1430,940,100,36,'#FFC168',true,true);pages.push(frame(i+1,`Clue ${i} of 3`,body));}
let reveal=t('THE PLAYER IS',70,290,940,105,51,'#F4F7FB')+panel(70,460,940,295,true)+t(e(data.player.toUpperCase()),105,525,870,165,data.player.length>16?42:55,'#FF8A32',false,true)+panel(70,820,940,850,false)+t('THE THREE CLUES',70,845,940,70,33,'#F4F7FB');for(let j=0;j<3;j++)reveal+=t(`0${j+1}`,75,970+j*132,90,60,38,'#FF8A32',true)+t(e(data.clues[j].toUpperCase()),170,970+j*132,820,80,data.clues[j].length>37?32:36,'#F4F7FB',true);reveal+=t('Play today’s mystery player',70,1460,940,65,43,'#F4F7FB',true,true)+t('at playfactsoverfeelings.com',70,1530,940,70,37,'#FFC168',true,true);pages.push(frame(5,'The reveal',reveal));
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage({viewport:{width:1080,height:1920},deviceScaleFactor:1});for(let i=0;i<5;i++){await page.setContent(pages[i]);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,`slide-${i+1}.png`)});}}finally{await browser.close();}
const py=process.env.PYTHON_EXE??'python';const enc=spawnSync(py,[path.join(project,'encode.py'),out],{encoding:'utf8',stdio:'inherit'});if(enc.status!==0)throw Error('Video encoding failed');
const edition=data.date?` — ${data.date}`:'';
const caption=`How many clues did you need? Drop your guess before the reveal.\n\nPlay the daily mystery at playfactsoverfeelings.com\n\n#NBATrivia #BasketballTrivia #GuessThePlayer #NBAHistory #FactsOverFeelings`;
await fs.writeFile(path.join(out,'post.txt'),`TITLE\nCan You Guess This NBA Legend in 3 Clues?${edition}\n\nCAPTION\n${caption}\n`);await fs.writeFile(path.join(out,'sources.json'),JSON.stringify(data.sources??[],null,2));console.log(path.join(out,'mystery-player.mp4'));
